server.port=8080

# Razorpay
spring.h2.console.path=/h2-console
razorpay.keyId=rzp_test_S6zTuDc8KZNHf6
razorpay.keySecret=aLZvlCu4fCdcXccbv8z0ds4Q
razorpay.webhookSecret=whsec_xxxxx

# DB
spring.datasource.url=jdbc:h2:mem:paymentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

